# Generated by Django 4.2 on 2023-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltr0n_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNI', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('RUC', models.CharField(blank=True, max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
